### PR TITLE
Added default_prefix to the VirtualHost dispatcher

### PR DESCRIPTION
**Pull request by skagget77**
If the incoming "Host" request header isn't found the in the domains dictionary the default_prefix is
prepended to the URL path instead of "". The default value of default_prefix is "" so it remains backwards compatible.

### CODE REVIEW

**Comment by nicklasb** [comment]
@skagget77 It is likely that this repo will be moved/renamed and another repo will be created here with the same name as this as CherryPy is probably moving completely to github in the near future. 
Just so you know that this PR will probably have to be redone.

**Comment by nicklasb** [comment]
@skagget77 it might not, actually. Forget the above. :-)

**Comment by skagget77** [comment]
@nicklasb Consider it done. :-)

**Comment by nicklasb** [comment]
Remember it again...
We regret to having to tell you, but when migrating the bitbucket repository issues, the ids of the issues would not match if we didn't create a new repository, please reappy all PRs to the new one, at: https://github.com/cherrypy/cherrypy

**Pull request closed without merging**
